name: Build and Package

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'The source branch or ref to build from'
        default: 'main'
        required: true
      release_name:
        description: 'The name for the release'
        required: true
            
jobs:
  release:
    environment: OSSign
    runs-on: windows-2022

    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          repository: 'shriprem/StayAwake'
          ref: ${{ github.event.inputs.source_branch }}

      - name: Add msbuild (Visual Studio 2022)
        uses: microsoft/setup-msbuild@v3
        with:
          vs-version: '17.0'

      - name: MSBuild of application exe
        working-directory: StayAwake
        run: |
          mkdir signed
          msbuild StayAwake.vcxproj /m /p:configuration="Release" /p:platform="x64"
          mv bin64/StayAwake.exe signed/StayAwake-x64.exe
          msbuild StayAwake.vcxproj /m /p:configuration="Release" /p:platform="Win32"
          mv bin/StayAwake.exe signed/StayAwake-win32.exe

      - name: Generate SHA256 hash for application_x64
        shell: pwsh
        run: |
          $hash64 = Get-FileHash -Path "signed\StayAwake-x64.exe" -Algorithm SHA256 | Select-Object -ExpandProperty Hash
          $hash = Get-FileHash -Path "signed\StayAwake-win32.exe" -Algorithm SHA256 | Select-Object -ExpandProperty Hash
          $lowHash64 = $hash64.ToLower()
          $lowHash = $hash.ToLower()
          echo "StayAwake.exe (64-bit) ===> SHA256 Hash: $lowHash64"
          echo "StayAwake.exe (Win32) ===> SHA256 Hash: $lowHash"

      - name: Sign files
        uses: ossign/ossign@main
        with:
          config: ${{ secrets.OSSIGN_CONFIG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          installOnly: false
          inputFiles: |
            signed/*.exe
          fileType: pecoff

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            signed/*
          name: ${{ github.event.inputs.release_name }}
          tag_name: ${{ github.run_id }}
          body: |
            # Signed Release ${{ github.event.inputs.release_name }}
            
            These are the distributable files for the signed release of StayAwake ${{ github.event.inputs.release_name }}
            
            The source code was fetched from https://github.com/shriprem/StayAwake/tree/${{ github.event.inputs.source_branch }}
            

          

